---
- hosts: digitalocean
  name: DigitalOcean

  tasks:
  - name: add user
    user:
      name: trauma
      # python -c "from passlib.hash import sha512_crypt; import getpass; print(sha512_crypt.using(rounds=5000).hash(getpass.getpass()))"
      password: $6$f1.2izO/uk8ilEY7$FhTVVVNtLkZ7Mm1D4DEYnPNEwbiOtIVvsfbbCE0gDMYvIXAr06SYqAOEhmHHWPOHT49zmtJk9kP4ussGxrFoc/
      state: present
      groups:
        - sudo
      shell: /bin/bash
      home: /home/trauma
      createhome: yes
      system: yes
      
  - name: add ssh key
    authorized_key:
      user: trauma
      key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
      state: present
      
  - name: update apt
    apt:
      update_cache: yes

  - name: update server
    apt:
      upgrade: yes
      update_cache: yes
  
  # - name: disable root login
  #   lineinfile:
  #     path: /etc/ssh/sshd_config
  #     regexp: "^PermitRootLogin"
  #     line: "PermitRootLogin no"
  #     state: present
  #     backup: yes

  - name: reboot server
    reboot:
      msg: "Reboot Initiated"
      connect_timeout: 5
      reboot_timeout: 600
      pre_reboot_delay: 0
      post_reboot_delay: 0
      test_command: uptime